# Site Info
title: Entre ceros y unos
tagline: 'Entre ceros y unos || Tecnología y algo más'
description: 'Entre ceros y unos es el blog personal de Alex Pérez, un gallego que trabaja programando y disfruta viajando'
keywords: 'programación,raspberry,raspberrypi,iot,linux,programming,software,travel,viajes,viajar,fotografía,photo,photography'
baseurl: ''
url: 'http://www.alejandroperezlopez.com'
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/page:num'
permalink: pretty

# About/contact
author:
  name: '@alexperezl'
  description: Software Engineer como trabajo, mi hobby es hacer fotos
  gravatar: 18faac89ab3ca2c4474710bc232dcca1 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/alejandroperezl
    github:    https://github.com/alejandroperezlopez
    instagram: https://www.instagram.com/alexperezl
    flickr:    https://www.flickr.com/photos/alejandroperezl
    twitter:   https://twitter.com/alexperezl

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
    - { Categorías: '/categories/' }
    - { Tags: '/tags/' }
  Sobre mí:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

# Puglins
google_analytics_token: 'UA-108250834-1' # leave blank if you don't want google analytics
disqus_short_name:  # leave blank if you don't want disqus

